apiVersion: v1
kind: Service
metadata:
  name: {{ include "policy-hub.fullname" . }}-frontend
  labels:
    {{- include "policy-hub.labels" . | nindent 4 }}
    app.kubernetes.io/name: policy-hub-frontend
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
