{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "policy-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.keys.dbPassword }}: {{ .Values.secret.dbPassword | quote }}
  {{ .Values.secret.keys.authPassword }}: {{ .Values.secret.authPassword | quote }}
{{- end }}
---
{{- if .Values.ghcrCreds.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ghcrCreds.name }}
  labels:
    {{- include "policy-hub.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ dict "auths" (dict .Values.ghcrCreds.registry (dict "username" .Values.ghcrCreds.username "password" .Values.ghcrCreds.password "auth" (printf "%s:%s" .Values.ghcrCreds.username .Values.ghcrCreds.password | b64enc))) | toJson | b64enc }}
{{- end }}
