services:
  policy-frontend-mocks:
    container_name: policy-frontend
    build:
      context: .
      dockerfile: cicd/docker/Dockerfile.mocks
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - "mocks"

  policy-frontend-dev:
    container_name: policy-frontend
    build:
      context: .
      dockerfile: cicd/docker/Dockerfile.development
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - "development"
