-- V1: Create policies table
-- Uses UUID primary key generated by PostgreSQL and JSONB for flexible policy content

CREATE TABLE policies
(
    id          UUID                     NOT NULL DEFAULT gen_random_uuid(),
    name        VARCHAR(255)             NOT NULL,
    description TEXT,
    status      VARCHAR(50)              NOT NULL,
    content     JSONB,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    CONSTRAINT pk_policies PRIMARY KEY (id),
    CONSTRAINT chk_policies_status CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);

-- Index on status for filtered queries (e.g. all active policies)
CREATE INDEX idx_policies_status ON policies (status);

-- GIN index on content for efficient JSONB queries (ADR: jsonb support)
CREATE INDEX idx_policies_content ON policies USING GIN (content);
