package org.constructx.policyhub.policies.api.dto;

import com.fasterxml.jackson.databind.JsonNode;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import org.constructx.policyhub.policies.domain.PolicyCategory;

import java.util.List;

public record CreatePolicyRequest(

        @Schema(
                description = "Unique business identifier defined by the client",
                example = "zugriff-konsortium-mitglieder",
                minLength = 1,
                maxLength = 200
        )
        @NotBlank(message = "policyId must not be blank")
        @Size(max = 200, message = "policyId must not exceed 200 characters")
        String policyId,

        @Schema(
                description = "Policy category",
                example = "ACCESS"
        )
        @NotNull(message = "category is required")
        PolicyCategory category,

        @Schema(
                description = """
                        Ordered list of policy constraints. Supported types are
                        MEMBERSHIP, USE_CASE, END_DATE and FRAMEWORK_AGREEMENT.
                        END_DATE is only allowed for CONTRACT policies.
                        """,
                example = """
                        [
                          {
                            "type": "MEMBERSHIP",
                            "value": "active"
                          },
                          {
                            "type": "USE_CASE",
                            "useCases": [
                              "UC.quality-assurance",
                              "UC.material-testing"
                            ]
                          }
                        ]
                        """
        )
        @NotNull(message = "constraints are required")
        List<JsonNode> constraints,

        @Schema(
                description = """
                        German legal text generated by the frontend.
                        It is persisted and returned unchanged by the backend.
                        """,
                example = "Der Zugriff ist ausschließlich aktiven Mitgliedern gestattet.",
                minLength = 1
        )
        @NotBlank(message = "legalText must not be blank")
        String legalText
) {
}