package org.constructx.policyhub.policies.api.dto;

import com.fasterxml.jackson.databind.JsonNode;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.constructx.policyhub.policies.domain.PolicyCategory;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

@Getter
@AllArgsConstructor
@Schema(description = "Persisted Policy Hub policy")
public class PolicyResponse {

    @Schema(
            description = "Backend-generated technical identifier of the policy",
            example = "00000000-0000-0000-0000-000000000001"
    )
    private final UUID id;

    @Schema(
            description = "Unique business identifier defined by the client",
            example = "oeffentlicher-zugriff-projektdokumentation"
    )
    private final String policyId;

    @Schema(
            description = "Policy category",
            example = "ACCESS",
            allowableValues = {"ACCESS", "CONTRACT"}
    )
    private final PolicyCategory category;

    @Schema(
            description = """
                    Ordered list of structured policy constraints.
                    Supported types are MEMBERSHIP, USE_CASE, END_DATE and
                    FRAMEWORK_AGREEMENT. END_DATE is only allowed for CONTRACT policies.
                    """,
            example = """
                    [
                      {
                        "type": "MEMBERSHIP",
                        "value": "active"
                      },
                      {
                        "type": "USE_CASE",
                        "useCases": [
                          "UC.quality-assurance",
                          "UC.material-testing"
                        ]
                      }
                    ]
                    """
    )
    private final List<JsonNode> constraints;

    @Schema(
            description = """
                    German legal text generated by the frontend,
                    persisted and returned unchanged by the backend.
                    """,
            example = "Der Zugriff ist ausschließlich aktiven Mitgliedern gestattet."
    )
    private final String legalText;

    @Schema(
            description = "Creation timestamp in ISO-8601 format",
            example = "2026-03-15T10:30:00Z"
    )
    private final Instant createdAt;

    @Schema(
            description = "Timestamp of the most recent update in ISO-8601 format",
            example = "2026-04-29T09:40:00Z"
    )
    private final Instant updatedAt;
}